### ISSUE TITLE
Missing project.clj file

### ISSUE THREAD

**Issue by Grahack** [day8/re-frame-template#158]
Hi,  
Is there a good reason for the `project.clj` to be missing after a

    lein new re-frame my-project

Not sure what info I should add. Maybe:

    Leiningen 2.9.6 on Java 1.8.0_282 OpenJDK 64-Bit Server VM

Thanks.

**Comment by Grahack** [comment]
Also I had to do this:

    mv src/my-project/ src/cljs/

**Comment by superstructor** [comment]
`project.clj` was removed as of [v2.0.0](https://github.com/day8/re-frame-template/blob/master/CHANGELOG.md#200-2021-03-31).

Instead of generating a Leiningen-based build, this template now generates a build that only depends on `shadow-cljs`. This has benefits in terms of 
- `shadow-cljs` and `npm`/`yarn` integration
- auto-reloading of all configuration, including shadow-cljs build configuration
- beginners or people looking for support on the #shadow-cljs channel on Clojurians Slack.

I'm guessing you had to `mv src/my-project/ src/cljs/` because you supplied your own `project.clj`, possibly with a different source paths config than the `shadow-cljs.edn` configuration that is generated ?

**Comment by Grahack** [comment]
Thanks for this explanation and indeed I supplied my own `project.clj` with a different path.

And thanks for all the nice software you provide! Have fun!
