### ISSUE TITLE
Adding posh option

### ISSUE THREAD

**Issue by kristianmandrup** [Day8/re-frame-template#22]
Tried to add [posh](https://github.com/mpdairy/posh) as an option.

After installing `lein install` from target folder of template build output

```
^C✘-INT ~/repos/clojure-projs/fun 
10:11 $ lein new re-frame +posh
clojure.lang.ExceptionInfo: Attempt to close section out of order: re-com? at line 7, column 44
 at stencil.parser$parse_tag.invoke (parser.clj:258)
```

```cljs
(defproject {{ns-name}} "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.7.170"]
                 [reagent "0.6.0-alpha"]
                 [re-frame "0.7.0-alpha"]{{#re-com?}}
                 [posh "0.3.4"]{{#posh?}}
---> line 7 [re-com "0.8.0"]{{/re-com?}}{{#routes?}}
                 [secretary "1.2.3"]{{/routes?}}{{#garden?}}
                 [garden "1.3.1"]{{/garden?}}{{#handler?}}
                 [compojure "1.4.0"]
                 [ring "1.4.0"]{{/handler?}}]
```

I'm just guessing here... what does `{{#posh?}}` do? how do I fix it?
This is my `posh` options file:

```cljs
(ns leiningen.new.options.posh
  (:require [leiningen.new.options.helpers :as helpers]))

(def option "posh")

(defn files [data]
  [["src/clj/{{sanitized}}/conn.clj" (helpers/render "src/cljs/conn.cljs" data)]
   ["src/clj/{{sanitized}}/queries.clj" (helpers/render "src/cljs/queries.cljs" data)]])
```

**Comment by gadfly361** [comment]
@kristianmandrup 

Try changing this:
```
[re-frame "0.7.0-alpha"]{{#re-com?}}
[posh "0.3.4"]{{#posh?}}
[re-com "0.8.0"]{{/re-com?}}{{#routes?}}
```

To this:

```
[re-frame "0.7.0-alpha"]{{#re-com?}}
[re-com "0.8.0"]{{/re-com?}}{{#posh?}}
[posh "0.3.4"]{{/posh?}}{{#routes?}}
```
This is like mustahce: `{{#posh?}} XXX {{/posh?}}`. So when someone adds the `+posh` when they create the template, then `posh?` will be set to true, and `XXX` will get dropped in to the resulting template, otherwise it'll be left out. So in your attempt above, the lines between posh and re-com were mixed.  Also, be sure to add posh? to [here](https://github.com/Day8/re-frame-template/blob/master/src/leiningen/new/re_frame.clj)

**Comment by kristianmandrup** [comment]
Awesome! Thanks :) I didn't recognise the mustache syntax. 
Reminds me of Ember days of old.
