### ISSUE TITLE
Upgrade - Clojure 1.8 and Clojurescript 1.8.x

### ISSUE THREAD

**Issue by corporatepiyush** [Day8/re-frame-template#25]
Does it works with latest versions,  Clojure 1.8 and Clojurescript 1.8.40 ?

If yes, its time to update the project.clj generated

**Comment by gadfly361** [comment]
Since this template is pinned to figwheel, I generally try to follow what [bruce recommends](https://github.com/bhauman/lein-figwheel#usage), which looks like it's still clojure 1.7. Also, I think re-frame is still on 1.7.

That said, if @mike-thompson-day8, @danielcompton et al. have no objections, and I can bump.

**Comment by danielcompton** [comment]
TBH we haven't actually tested it on the latest versions of ClojureScript, so I wouldn't be comfortable just merging this. A template is a one-off generator anyway, so people will need to upgrade their Clojure and ClojureScript versions themselves after the first time. Once we upgrade to the newest CLJS version, we would look at updating the template.

**Comment by fasiha** [comment]
Been running latest Clojure & Clojurescript & re-frame & reagent for a few weeks now. No problems.
