### ISSUE TITLE
Add devcards as optional profile

### ISSUE THREAD

**Issue by smahood** [Day8/re-frame-template#28]
Wondering if it would be of interest to anyone else to add devcards as an optional profile item.

**Comment by gadfly361** [comment]
If you or anyone knows how to wire it up, I'd be more than happy to accept a PR! I wasn't quite sure how to add devcards to work with re-frame .. so I put it on the shelf.  

For reference, I have added a +devcards profile to my vanilla reagent template, [reagent-figwheel](https://github.com/gadfly361/reagent-figwheel).  If you do make a PR, I'd prefer to keep it close-ish to that file structure - where all the devcards are in their own directory and the files end with `_card` in their name.

**Comment by gadfly361** [comment]
@smahood Have you (or anyone) found a good approach to devcards + re-frame? I remember some chatter a while back on the slack channel, but I didn't follow it closely enough to know if there was a resolution.

**Comment by smahood** [comment]
This is the closest thing I've got in my notes, but I haven't had time to dive in to it yet.
https://github.com/nberger/devcards/blob/iframe/example_src/devdemos/re_frame.cljs

**Comment by Conaws** [comment]
Personally, I don't think the devcards have to be wired up with the larger re-frame app at all.  When I'm doing devcards stuff I often am just playing with a sample ratom that only has the data that matters to that component.  When I am testing out subscriptions/handlers etc, I often will use namespaced keywords for the subscriptions and handlers so that the card experiments are confined to a section of my app state.

**Comment by gadfly361** [comment]
Given that devcards and re-frame just don't play nicely with each other, I am going to close this issue.  Happy to reopen if more discussion is desired though :)
