### ISSUE TITLE
All ClojureScript build config :output-dir parameters should be unique

### ISSUE THREAD

**Issue by maacl** [Day8/re-frame-template#33]
Upon `cider-jack-in-clojurescript` I get:

    All ClojureScript build config :output-dir parameters should be unique

param for `:output-dir` in both the `dev` and `min` profile appears to be the same. Param for `dev` is eual to the default value ie. `resources/public/js/compiled/out` which is causing the issue. 

Confirm @Robsteranium below that changing to unique params fixes issue.

**Comment by Robsteranium** [comment]
Confirmed. I would guess this is due to (bhauman/lein-figwheel#453).
```
All ClojureScript build config :output-dir parameters should be unique

  {:cljsbuild
   {:builds
    [{:compiler
      {:output-to "resources/public/js/compiled/test.js"
       :main type-invaders.runner
       :optimizations :none
       :output-dir ...
       ^---- 
       }}]}}
```
In any case,  adding a unique `:output-dir` parameter to the test build in my project.clj appears to have resolved the problem.

re-frame/lein-template/0.2.4, lein-figwheel 0.5.7, lein-cljsbuild 1.1.4
CIDER 0.13.0 (California), nREPL 0.2.12, Clojure 1.8.0, Java 1.8.0_91

**Comment by gadfly361** [comment]
@maacl @Robsteranium Thanks for bringing up and confirming this issue! Will try to fix in the next cut :)
