### ISSUE TITLE
Add useful aliases

### ISSUE THREAD

**Issue by dundalek** [Day8/re-frame-template#55]
I use following aliases to make development easier, to build all assets by a single lein command:

```clojure
  :aliases {"dev" ["do" "clean"
                        ["pdo" ["figwheel" "dev"]
                               ["less" "auto"]]]
            "build" ["do" "clean"
                          ["cljsbuild" "once" "min"]
                          ["less" "once"]]}
```

Would you be interested to add these into the template?

**Comment by danielcompton** [comment]
Looks interesting, will leave it up to @gadfly361 to make the call.

What's `pdo`? You probably realise this, but keep in mind that any change will need to handle `+less` not being part of the template.

**Comment by gadfly361** [comment]
@dundalek One of the goals of re-frame-template is to allow users to **opt-in** (to avoid bloat/noise).  Since many users will never use aliases, I think there are two possible options:

1. Add documentation to this template's README (not the generated readme), giving examples/links of how to use aliases.
2. Add a `+aliases` profile.  As @danielcompton noted, this would need to account for varying profile combinations. This option is likely more useful, but will also make the template more cumbersome to test going forward. That said, I think it could be a worthwhile addition.

@dundalek If you are interested, I would be happy to review and help with a PR for either option :)

**Comment by dundalek** [comment]
@danielcompton `pdo` runs things parallel which is needed because those tasks watch for file changes and run indefinitely. Good point about variations, will probably need to also handle a case when `+garden` is used.

@gadfly361 Thanks, I like `+aliases` profile option. I will try it out.
